DROP TABLE IF EXISTS user_account;

CREATE TABLE user_account(
	id 	INT(11)		NOT NULL 	AUTO_INCREMENT PRIMARY KEY, 
	name	VARCHAR(14) 	NOT NULL 	UNIQUE KEY,
	pass	VARCHAR(14) 	DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

#DESCRIBE user_account;

#SHOW INDEXES FROM user_account \G;
